name: Train Model

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install wandb

      # Step 4: Run training script
      - name: Train model
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          python train.py

      # Step 5: Archive model and training logs (Optional)
      - name: Archive model and logs
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: Inception_V3.h5
