name: Train and Upload Model to W&B

on:
  workflow_dispatch:  # เพื่อให้สามารถเรียกใช้งาน workflow ด้วยมือได้

jobs:
  train_and_upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install wandb

      # Step 4: Set up Weights & Biases API Key
      - name: Set WANDB_API_KEY
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}  # ต้องตั้งค่า WANDB_API_KEY ใน GitHub Secrets
        run: |
          echo "WANDB_API_KEY is set."

      # Step 5: Train the model
      - name: Train model
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          python train.py

      # Step 6: List files (verify model saved)
      - name: List files in directory
        run: |
          ls -al

      # Step 7: Save model as artifact (Optional)
      - name: Save model as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Inception_V3_model
          path: Inception_V3.h5
