name: Train and Upload Model

on:
  workflow_dispatch:

jobs:
  train_and_upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install wandb huggingface_hub

      # Step 4: Run training script
      - name: Train model
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          python train.py

      # Step 5: List files (verify model saved)
      - name: List files in directory
        run: |
          ls -al

      # Step 6: Save model as artifact
      - name: Save model as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Inception_V3_model
          path: Inception_V3.h5

      # Step 7: Upload model to Hugging Face
      - name: Upload model to Hugging Face
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: |
          huggingface-cli upload Inception_V3.h5 Suphawan/Melanoma-3 --repo-type model --token $HF_API_TOKEN
