name: Upload Model to Hugging Face

on:
  workflow_dispatch:
  push:
    paths:
      - "Inception_V3.h5"  # รัน workflow เมื่อไฟล์โมเดลเปลี่ยนแปลง

jobs:
  upload_model:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install huggingface_hub

      # Step 4: Upload model to Hugging Face
      - name: Upload model to Hugging Face
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: |
          python upload_model.py
